name: benchmark
description: "Fairy Framework Performance Benchmarks"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.2
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_riverpod: ^2.6.1
  # Add path to local fairy package
  fairy:
    path: ../src

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
